apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  labels:
    app: $APP_NAME
    env: prod
    version: $VERSION
spec:
  type: LoadBalancer
  selector:
    app: $APP_NAME-$VERSION
    version: $VERSION
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080